# nested_list=['vijay','prasanth',[23,22],[True,False]]
# print(nested_list[0])
# print(nested_list[1])
# print(nested_list[2][0])
# print(nested_list[2][0:2])
# print(nested_list[3][0:2])

nested_list = (['Shubham','ketan'],[21,22],(True,False))
print(nested_list[0][0])
print(nested_list[0][1])
print(nested_list[1][0])
print(nested_list[1][1])
print(nested_list[2][0])
print(nested_list[2][1])
print(nested_list[2][0:2])